import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeScript = `
    (function () {
      try {
        var KEY = 'theme_preference';
        var getPreference = function () {
          var value = localStorage.getItem(KEY);
          if (value === 'light' || value === 'dark' || value === 'system') return value;
          return 'system';
        };
        var getSystemTheme = function () {
          return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
        };
        var apply = function (preference) {
          var resolved = preference === 'system' ? getSystemTheme() : preference;
          document.documentElement.classList.toggle('dark', resolved === 'dark');
          document.documentElement.style.colorScheme = resolved;
        };

        apply(getPreference());

        var media = window.matchMedia('(prefers-color-scheme: dark)');
        var onSystemChange = function () {
          if (getPreference() === 'system') apply('system');
        };

        if (media.addEventListener) {
          media.addEventListener('change', onSystemChange);
        } else if (media.addListener) {
          media.addListener(onSystemChange);
        }

        window.addEventListener('storage', function (event) {
          if (event.key === KEY) apply(getPreference());
        });

        window.addEventListener('theme-preference-change', function () {
          apply(getPreference());
        });
      } catch (e) {}
    })();
  `;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
